site_name: Adafruit For Newbies
site_url: https://adafruit.usedgoodies.com/

theme:
    name: mkdocs
    locale: en
    highlightjs: true
    hljs_style: agate
    nav_style: dark

nav:
    - Home: index.md
    - Getting Started: 
        - Overview: getting-started/index.md
        - How Website is Organized: getting-started/website-structure.md
    - Hardware: 
        - Overview: hardware/index.md
        - Choosing a Board: hardware/choosing_a_board.md
    - CircuitPython: 
        - Overview: circuitpython/index.md
        - Installation: circuitpython/installation.md
    - Glossary: 
        - Index: glossary/index.md
        - Adafruit IO: glossary/adafruit_io.md
        - AirLift: glossary/airlift.md
        - Backpack: glossary/backpack.md
        - Bundlefly: glossary/bundlefly.md
        - Cape: glossary/cape.md
        - Circuit Playground: glossary/circuit_playground.md
        - Clue: glossary/clue.md
        - Connectors: glossary/connectors.md
        - Crickit: glossary/crickit.md
        - Feather: glossary/feather.md
        - FeatherWing: glossary/feather#featherwing
        - Glider: glossary/glider.md
        - GPIO: glossary/gpio.md
        - Grove: glossary/connectors#grove
        - HAT: glossary/hat.md
        - I2C: glossary/i2c.md
        - IOT: glossary/iot.md
        - Itsy Bitsy: glossary/itsy_bitsy.md
        - JST: glossary/connectors#jst
        - Metro: glossary/metro.md
        - Microcontroller: glossary/microcontroller.md
        - Neopixel: glossary/neopixel.md
        - PyLeap: glossary/pyleap.md
        - PWM: glossary/pwm.md
        - QT Py: glossary/qt_py.md
        - QWIIC: glossary/connectors#qwiic
        - RP2040: glossary/rp2040.md
        - Shield: glossary/shield.md
        - SPI: glossary/spi.md
        - STEMMA: glossary/connectors#stemma
        - STEMMA QT: glossary/connectors#stemma-qt
        - Teensy: glossary/teensy.md
        - WipperSnapper: glossary/wippersnapper.md
    - Contact Us: contact.md

markdown_extensions:
    - toc:
        permalink:
    - admonition
    - attr_list
    - def_list

copyright: Copyleft &copy; 2022 <a href="https://github.com/jliu70">Jeff Liu</a>

